name: Deploy

on:
  workflow_run:
    workflows: [ CI ]
    types: [ completed ]
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

env:
  IMAGE_NAME: ghcr.io/michael-bailey/personal_website

jobs:
  update-prod:
    name: Update prod state
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v5

      - uses: imranismail/setup-kustomize@v2

      - name: Fetch master
        run: git fetch

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout prod for yaml changes
        run: |
          git switch prod
          git reset --hard master

      - name: Update image tag
        # Btw if this works, this is dumb
        working-directory: deploy/kustomise/overlays/prod
        run: |
          kustomize edit set image ${{ env.IMAGE_NAME }}=${{ env.IMAGE_NAME }}:${{ github.event.workflow_run.head_sha }}

      - name: Commit new tag to prod
        run: |
          git add -A
          git commit -m "updated kustomize to version: ${{ github.event.workflow_run.head_sha }}"

      - name: Push
        run: git push -f